# https://probot.github.io/apps/boring-cyborg/
---
labelPRBasedOnFilePath:
  project:
    - ./*
  sources:
    - src/**/*
  tests:
    - tests/**/*
    docs:
    - docs/**/*

firstIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!
