---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "TomerFi"
    assignees:
      - "TomerFi"
    labels:
      - "dependabot"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "TomerFi"
    assignees:
      - "TomerFi"
    labels:
      - "dependabot"
