# https://reporanger.com/
---
default:
  close:
    comment: "⚠️ This issue has been marked $LABEL and will be closed in $DELAY."
    delay: 1d

merges:
  - action: delete_branch

labels:
  duplicate:
    action: close
    delay: 15s
  wontfix: close
  invalid: close
  stale:
    action: close
    comment: false
  'merge when passing': merge
  dependabot: merge

comments:
  - action: label
    pattern: /duplicate of/i
    labels:
      - duplicate

commits:
  - action: label
    pattern: BREAKING CHANGE
    labels:
      - Major Version
  - action: label
    pattern: /perf.+?:/
    labels:
      - Major Version
  - action: label
    pattern: /feat.+?:/
    labels:
      - Minor Version
  - action: label
    pattern: /fix.+?:/
    labels:
      - Patch Version
  - action: label
    pattern: /merge when passing/i
    labels:
      - merge when passing
