codecov:
  branch: unit
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "20...100"
  status:
    patch: yes
    changes: no
    project:
      default:
        target: 30
        threshold: 0.09

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
