sudo: false
language: python
matrix:
  fast_finish: true
  include:
    - python: "3.5.3"
      name: "Python 3.5.3 Lint tests (flake8, pydocstyle, pycodestyle)"
      env: TOXENV=lint
    - python: "3.5.3"
      name: "Python 3.5.3 Pylint test"
      env: TOXENV=pylint
    - python: "3.5.3"
      name: "Python 3.5.3 Static-Typing test"
      env: TOXENV=typing
    - python: "3.5.3"
      name: "Python 3.5.3 Pytest with coverage reports"
      env: TOXENV=cov
      after_success: 
        - coveralls
        - codecov
    - python: "3.5.3"
      name: "Python 3.5.3 Unit tests"
      env: 
        - TOXENV=py35
        - CI_SOURCE=TravisCI
    - python: "3.6"
      name: "Python 3.6 Unit tests"
      env: TOXENV=py36
    - python: "3.7"
      name: "Python 3.7 Unit tests"
      env: TOXENV=py37
      dist: xenial
git:
  quiet: true
env:
  global:
     - CI_SOURCE=TravisCI
install:
  - travis_retry pip install tox coveralls codecov
script:
  - travis_wait tox
