language: python
matrix:
  fast_finish: true
  include:
    - python: "3.5.3"
      env: TOXENV=lint
    - python: "3.5.3"
      env: TOXENV=pylint
    - python: "3.5.3"
      env: TOXENV=typing
    - python: "3.5.3"
      env: TOXENV=cov
    - python: "3.5.3"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
script:
  - travis_wait tox
