[build-system]
requires = ["poetry~=1.0.5"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "aioswitcher"
version = "0.1.0"
description = "Switcher Boiler Unofficial Bridge and API."
license = "MIT"
authors = ["Tomer Figenblat <tomer.figenblat@gmail.com>"]
readme = "README.md"
homepage = "https://pypi.org/project/aioswitcher/"
repository = "https://github.com/tomerfi/aioswitcher"
documentation = "https://aioswitcher.readthedocs.io"
keywords = ["home", "automation", "switcher", "water-heater"]
classifiers = [
    "Framework :: AsyncIO",
    "Framework :: tox",
    "Framework :: Pytest",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.7",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Home Automation",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed"
]
include = [] # CAHNGELOG, LICENSE, README and pyproject.toml are automatically included
exclude = [
    ".*",
    "dist",
    "docs",
    "tests",
    "CODE_OF_CONDUCT.md",
    "mypy.ini",
    "pylintrc",
    "*__pycache__*",
    "*.pyc"
] # poetry.lock is automatically excluded

[tool.poetry.dependencies]
python = "^3.7"
asynctest = { version = "0.13.0", optional = true }
bandit = { version = "1.6.2", optional = true }
black = { version = "19.10b0", optional = true }
doc8 = { version = "0.8.0", optional = true }
flake8 = { version = "3.7.9", optional = true }
flake8-docstrings = { version = "1.5.0", optional = true }
isort = { version = "4.3.21", optional = true }
mypy = { version = "0.770", optional = true }
pygments = { version = "2.6.1", optional = true }
pytest = { version = "5.2.2", optional = true }
pytest-aiohttp = { version = "0.3.0", optional = true }
pytest-asyncio = { version = "0.10.0", optional = true }
pytest-cov = { version = "2.8.1", optional = true }
pytest-sugar = { version = "0.9.2", optional = true }
sphinx = { version = "2.4.4", optional = true }
sphinx-rtd-theme = { version = "0.4.3", optional = true }
toml = { version = "0.10.0", optional = true }
yamllint = { version = "1.20.0", optional = true }

[tool.poetry.extras]
docs= ["pygments", "sphinx", "sphinx-rtd-theme", "toml"]
checkers = [
    "asynctest",
    "bandit",
    "black",
    "doc8",
    "flake8",
    "flake8-docstrings",
    "isort",
    "mypy",
    "pytest",
    "toml",
    "yamllint"
]
tests = [
    "asynctest",
    "pytest",
    "pytest-aiohttp",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-sugar"
]

[tool.isort]
line_length = 79

[tool.black]
line-length = 79
target-version = ["py37"]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist =
    update-poetry
    checkers
    py{37}
isolated_build = true
minversion = 3.13.1
requires = poetry>=1.0.5
skip_missing_interpreters = true
skipdist = true

[testenv]
basepython = python3.7
skip_install = true
whitelist_externals = poetry

[testenv:update-poetry]
commands = poetry update

[testenv:checkers]
commands =
    poetry install -vv -E "checkers" -E "docs"
    yamllint --config-file .yamllint --format colored --strict .
    bandit -rvc .bandit src/ tests/ docs/source/ -l -ii
    isort --check-only --recursive src/ tests/ docs/source/
    flake8 --statistics --count --doctests src/ tests/ docs/source/
    black --check --diff src/ tests/ docs/source/
    mypy --follow-imports silent --ignore-missing-imports --show-error-codes src/ tests/ docs/source/
    doc8 --allow-long-titles --max-line-length 100 -e rst docs/source
    sphinx-build -W -b html -d {envtmpdir}/doctrees docs/source {envtmpdir}/html

[testenv:py37]
commands =
    poetry install -vv -E "tests"
    pytest -vs --cov --cov-config=.coveragerc

"""
