version: 2.1

executors:
  python-docker:
    parameters:
      tag:
        type: string
        default: 3.5.3-jessie
    docker:
      - image: circleci/python:<< parameters.tag >>
    working_directory: ~/project

commands:
  pre-command:
    description: update distribution
    steps:
      - run: sudo apt-get update

  install-requirements:
    description: install requirements.txt
    steps:
      - run: pip install -r --user requirements.txt

  install-test-requirements:
    description: install requirements_test.txt
    steps:
      - run: pip install -r --user requirements_test.txt

  install-check-manifest:
    description: install check manifest
    steps:
      - run: pip install -r --user check-menifest
      - run: check-manifest -v

  run-tests:
    description: run pytest unit testing
    steps:
      - run: pytest -vsx

  run-tests-with-coverage-report:
    description: run pytest unit testing
    steps:
      - run: pytest -vs --cov --cov-append --cov-config=.coveragerc

  run-linters:
    description: run flake8, pydocstyle and pydocstyle linters
    steps:
      - run: flake8 --statistics --count --doctests src/ tests/
      - run: pydocstyle -v --count src/ tests/
      - run: pycodestyle -v --statistics --show-pep8 --count src/ tests/

  run-pylint:
    description: run pylint
    steps:
      - run: pylint --disable fixme --rcfile pylintrc src/ tests/

  run-mypy:
    description: run mypy type checking
    steps:
      - run: mypy --config-file mypy.ini src/ tests/

jobs:
  python35-unittests:
    executor:
      name: python-docker
      tag: 3.5.3-jessie
    steps:
      - checkout
      - install-requirements
      - install-test-requirements
      - run-tests

workflows:
  version: 2.1
  build:
    jobs:
      - python35-unittests
