version: 2.1

executors:
  python-docker:
    parameters:
      tag:
        type: string
        default: "3.5.5"
    docker:
      - image: circleci/python:<< parameters.tag >>
    working_directory: ~/workspace
    environment:
      TZ: "Asia/Jerusalem"

commands:
  prepare-venv:
    description: Prepare the virtual environment
    parameters:
      py:
        type: string
        default: "3.5.5"
    steps:
      - restore_cache:
          keys:
            - v1-modules1-<< parameters.py >>-{{ .Branch }}-{{ checksum "MANIFEST.in" }}
      - run:
          name: Create venv for the python modules
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -q --upgrade pip setuptools
            pip install -q --progress-bar off -r requirements.txt
            pip install -q --progress-bar off -r requirements_test.txt
      - save_cache:
          key: v1-modules1-<< parameters.py >>-{{ .Branch }}-{{ checksum "MANIFEST.in" }}
          paths:
            - ./venv

  install-module:
    description: Install aioswitcher module
    steps:
      - run:
          name: Install
          command: |
            . venv/bin/activate
            pip install .

  check-manifest:
    description: Run check-manifest test
    steps:
      - run:
          name: Check-manifest
          command: |
            . venv/bin/activate
            check-manifest -v

  check-security:
    description: Run bandit tests
    steps:
      - run:
          name: Code-security
          command: |
            . venv/bin/activate
            bandit -rvc .bandit src tests -l -ii

  run-tests:
    description: Run pytest test cases
    steps:
      - run:
          name: Pytest
          command: |
            . venv/bin/activate
            pytest -vs

  run-tests-with-coverage:
    description: Run pytest test cases
    steps:
      - run:
          name: Pytest
          command: |
            . venv/bin/activate
            pytest -vs --cov --cov-config=.coveragerc --cov-report=xml:coverage_report/coverage.xml
      - persist_to_workspace:
          root: coverage_report/
          paths:
            - coverage.xml
      - store_artifacts:
          path: coverage_report
      - store_test_results:
          path: coverage_report

  run-linters:
    description: Run flake8, pydocstyle, pydocstyle and pylint linters
    steps:
      - run:
          name: Linters
          command: |
            . venv/bin/activate
            flake8 --statistics --count --doctests src/ tests/
            pydocstyle -v --count src/ tests/
            pycodestyle -v --statistics --show-pep8 --count src/ tests/
            pylint --disable fixme --rcfile pylintrc src/ tests/

  run-mypy:
    description: Run mypy type checking
    steps:
      - run:
          name: Mypy
          command: |
            . venv/bin/activate
            mypy --config-file mypy.ini src/ tests/

  publish-codverage:
    description: Publish code coverage to CodeCov and Codacy
    steps:
      - attach_workspace:
          at: coverage_report/
      - run:
          name: Coverage report publish
          command: |
            . venv/bin/activate
            codecov --file coverage_report/coverage.xml
            cp coverage_report/coverage.xml coverage_report/coverage_codacy.xml
            sed -i 's#venv/lib/python3.5/site-packages#src#g' coverage_report/coverage_codacy.xml
            python-codacy-coverage -vr coverage_report/coverage_codacy.xml

  pypi-deploy:
    description: Deploy package to pypi
    steps:
      - run:
          name: Bash shellscripts/pypi-depoly
          command: |
            . venv/bin/activate
            bash shellscripts/pypi-depoly.sh "$CIRCLE_TAG" "$PYPY_USER" "$PYPI_PASSWORD" "$PWD/setup.cfg"

jobs:
  python35-manifest:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-venv
      - check-manifest

  python35-linters:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-venv
      - run-linters

  python35-mypy:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-venv
      - run-mypy

  python35-security:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-venv
      - check-security

  python35-unittests:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-venv
      - install-module
      - run-tests-with-coverage

  python36-unittests:
    executor:
      name: python-docker
      tag: "3.6"
    steps:
      - checkout
      - prepare-venv:
          py: "3.6"
      - install-module
      - run-tests

  python37-unittests:
    executor:
      name: python-docker
      tag: "3.7.1"
    steps:
      - checkout
      - prepare-venv:
          py: "3.7.1"
      - install-module
      - run-tests

  python35-coverage-reports:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-venv
      - publish-codverage

  deploy-package-to-pypi:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-venv
      - pypi-deploy

workflows:
  version: "2.1"
  build:
    jobs:
      - python35-manifest

      - python35-linters:
          requires:
            - python35-manifest

      - python35-mypy:
          requires:
            - python35-manifest

      - python35-security:
          requires:
            - python35-manifest

      - python35-unittests:
          requires:
            - python35-linters
            - python35-mypy
            - python35-security

      - python36-unittests:
          requires:
            - python35-linters
            - python35-mypy
            - python35-security

      - python37-unittests:
          requires:
            - python35-linters
            - python35-mypy
            - python35-security

      - python35-coverage-reports:
          requires:
            - python35-unittests

      - deploy-package-to-pypi:
          context: tomerfi-pypi-credentials
          requires:
            - python35-coverage-reports
