---
name: Pages Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Release
    branches:
      - dev
    types:
      - completed

env:
  MAIN_PY_VER: 3.9

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    name: Build documentation site and deploy to GH-Pages
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.MAIN_PY_VER }}

      - name: Cache pip repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ env.MAIN_PY_VER }}

      - name: Prepare python environment
        run: |
          pip install -rrequirements.txt
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Cache poetry virtual environment
        uses: actions/cache@v2.1.6
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-${{ env.MAIN_PY_VER }}

      - name: Build documenation site
        run: |
          poe install_docs
          poe sphinx_clean_build

      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docsbuild
          cname: aioswitcher.tomfi.info
          commit_message: 'docs: deployed documentation site '
