---
name: Pre-Release

on:
  push:
    branches:
      - dev

jobs:
  pre-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]
    steps:
      - name: Source checkout
        uses: actions/checkout@v2

      - name: Cache pip repository
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}-${{ matrix.python }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache poetry repository
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-${{ matrix.python }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Build distribution assets
        run: |
          pip install --upgrade pip poetry
          poetry build

      - name: Create release
        uses: marvinpinto/action-automatic-releases@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: latest
          files: |
            dist/*.tar.gz
            dist/*.whl
