---
name: Release

on:
  push:
    tags:
      - '[2][0-9][2-9][0-9].[1-9][0-2]?.[1-9][0-9]?'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.0.0

      - name: Create release
        uses: actions/create-release@v1.0.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Changes in this Release
            - Test1
            - Test2
          draft: true
          prerelease: false
