---
name: Release

on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]*'

env:
  MAIN_PY_VER: 3.9

jobs:
  release:
    runs-on: ubuntu-latest
    environment: deployment
    name: Build and publish release
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.MAIN_PY_VER }}

      - name: Cache pip repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ env.MAIN_PY_VER }}

      - name: Prepare python environment
        run: |
          pip install -rrequirements.txt
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Cache poetry virtual environment
        uses: actions/cache@v2.1.6
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-${{ env.MAIN_PY_VER }}

      - name: Verify documenation site
        run: |
          poe install_docs
          poe sphinx_linkcheck
          poe sphinx_build
          poe sphinx_spelling

      - name: Publish development builds for thecode
        if: github.actor == 'thecode'
        run: poetry publish --build -u __token__ -p ${{ secrets.THECODE_PYPI_TOKEN }}

      - name: Publish development builds for tomerfi
        if: github.actor == 'TomerFi'
        run: poetry publish --build -u __token__ -p ${{ secrets.TOMERFI_PYPI_TOKEN }}

      - name: Create release
        id: create_release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            dist/*.tar.gz
            dist/*.whl

      - name: Tweet new release for thecode
        if: github.actor == 'thecode'
        uses: lazy-actions/tweet-action@1.0.1
        env:
          RELEASE_TAG: ${{ steps.create_release.outputs.automatic_releases_tag }}
        with:
          oauth_consumer_key: ${{ secrets.THECODE_TWITTER_API_KEY }}
          oauth_consumer_secret: ${{ secrets.THECODE_TWITTER_API_SECRET_KEY }}
          oauth_token: ${{ secrets.THECODE_TWITTER_ACCESS_TOKEN }}
          oauth_token_secret: ${{ secrets.THECODE_TWITTER_ACCESS_TOKEN_SECRET }}
          message: |
            🚀🎉 Aioswitcher ${{ env.RELEASE_TAG }} has been released! 🎉🚀
            ${{ github.event.repository.html_url }}/releases/tag/${{ env.RELEASE_TAG }}

            #aioswitcher

      - name: Tweet new release for tomerfi
        if: github.actor == 'TomerFi'
        uses: lazy-actions/tweet-action@1.0.1
        env:
          RELEASE_TAG: ${{ steps.create_release.outputs.automatic_releases_tag }}
        with:
          oauth_consumer_key: ${{ secrets.TOMERFI_TWITTER_API_KEY }}
          oauth_consumer_secret: ${{ secrets.TOMERFI_TWITTER_API_SECRET_KEY }}
          oauth_token: ${{ secrets.TOMERFI_TWITTER_ACCESS_TOKEN }}
          oauth_token_secret: ${{ secrets.TOMERFI_TWITTER_ACCESS_TOKEN_SECRET }}
          message: |
            🚀🎉 Aioswitcher ${{ env.RELEASE_TAG }} has been released! 🎉🚀
            ${{ github.event.repository.html_url }}/releases/tag/${{ env.RELEASE_TAG }}

            #aioswitcher
