# yamllint disable rule:line-length
---
name: Release

on:
  workflow_dispatch:

jobs:
  secrets_keys:
    runs-on: ubuntu-latest
    name: Determine secrets keys
    outputs:
      pypi_token: ${{ steps.output_keys.outputs.pypi_token }}
      twitter_api_key: ${{ steps.output_keys.outputs.twitter_api_key }}
      twitter_api_secret_key: ${{ steps.output_keys.outputs.twitter_api_secret_key }}
      twitter_access_token: ${{ steps.output_keys.outputs.twitter_access_token }}
      twitter_access_token_secret: ${{ steps.output_keys.outputs.twitter_access_token_secret }}
    steps:
      - name: Save keys as output
        id: output_keys
        run: |
          actor=echo ${{ github.actor }} | tr [:lower:] [:upper:]
          echo "::set-output name=pypi_token::$actor_PYPI_TOKEN"
          echo "::set-output name=twitter_api_key::$actor_TWITTER_API_KEY"
          echo "::set-output name=twitter_api_secret_key::$actor_TWITTER_API_SECRET_KEY"
          echo "::set-output name=twitter_access_token::$actor_TWITTER_ACCESS_TOKEN"
          echo "::set-output name=twitter_access_token_secret::$actor_TWITTER_ACCESS_TOKEN_SECRET""

  release:
    runs-on: ubuntu-latest
    needs: [secrets_keys]
    environment: deployment
    name: Build, publish, release, and announce
    env:
      MAIN_PY_VER: 3.9
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.MAIN_PY_VER }}

      - name: Cache pip repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ env.MAIN_PY_VER }}

      - name: Prepare python environment
        run: |
          pip install -rrequirements.txt
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Cache poetry virtual environment
        uses: actions/cache@v2.1.6
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-${{ env.MAIN_PY_VER }}

      - name: Configure git
        run: |
          git config --global user.name "${{ secrets.COMMITER_NAME }}"
          git config --global user.email "${{ secrets.COMMITER_EMAIL}}"

      - name: Determine version and create changelog
        id: bumper
        uses: tomerfi/version-bumper-action@1.0.0
        with:
          changelog: true

      - name: Set new project version
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: pyproject.toml
          key: tool.poetry.version
          value: ${{ steps.bumper.outputs.new_version }}

      - name: Commit, tag, and push
        run: |
          git add pyproject.toml
          git commit -m "build: bump version to ${{ steps.bumper.outputs.new_version }}"
          git push
          git tag ${{ steps.bumper.outputs.new_version }} -m ${{ steps.bumper.outputs.new_version }}
          git push origin ${{ steps.bumper.outputs.new_version }}

      - name: Verify documenation site build
        run: |
          poe install_docs
          poe sphinx_linkcheck
          poe sphinx_build
          poe sphinx_spelling

      - name: Publish build to PyPi
        run: poetry publish --build -u __token__ -p ${{ secrets[needs.secrets_keys.outputs.pypi_token] }}

      - name: Set development project version
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: pyproject.toml
          key: tool.poetry.version
          value: ${{ steps.bumper.outputs.next_dev_iteration }}

      - name: Commit and push
        run: |
          git add pyproject.toml
          git commit -m "build: bump version to ${{ steps.bumper.outputs.next_dev_iteration }}"
          git push

      - name: Release to GitHub
        id: gh_release
        uses: ncipollo/release-action@v1.8.9
        with:
          bodyFile: changelog-${{ steps.bumper.outputs.new_version }}.md
          tag: ${{ steps.bumper.outputs.new_version }}

      - name: Tweet new release
        uses: lazy-actions/tweet-action@1.0.1
        with:
          oauth_consumer_key: ${{ secrets[needs.secrets_keys.outputs.twitter_api_key] }}
          oauth_consumer_secret: ${{ secrets[needs.secrets_keys.outputs.twitter_api_secret_key] }}
          oauth_token: ${{ secrets[needs.secrets_keys.outputs.twitter_access_token] }}
          oauth_token_secret: ${{ secrets[needs.secrets_keys.outputs.twitter_access_token_secret] }}
          message: |
            🚀🎉 Aioswitcher ${{ steps.bumper.outputs.new_version  }} has been released! 🎉🚀
            ${{ steps.gh_release.outputs.html_url }}

            #aioswitcher
