---
name: Pre-Release

on:
  push:
    tags:
      #- '2[0-9][2-9][0-9].[1-9][0-2]?.[1-9][0-9]?'
      - '*.*.*'

jobs:
  pre-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.0.0

      - name: Cache pip repository
        uses: actions/cache@v1.1.2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}-${{ matrix.python }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache poetry repository
        uses: actions/cache@v1.1.2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-${{ matrix.python }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1.2.0
        with:
          python-version: ${{ matrix.python }}

      - name: Build distribution assets
        run: |
          pip install --upgrade pip poetry
          poetry build

      - name: Create release
        uses: marvinpinto/action-automatic-releases@v1.0.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          title: Pre-Release ${{ github.ref }}
          files: |
            dist/*.tar.gz
            dist/*.whl
